# Generated by Django 5.0.6 on 2024-07-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trigger",
            name="jsonpath_expression",
            field=models.CharField(
                help_text='Use <a href="http://json2jsonpath.com" target="_blank">JSONPath generator</a> with expected JSON payload.',
                max_length=200,
                verbose_name="JSONPath expression",
            ),
        ),
    ]
